### ISSUE TITLE
xenaAPI python package or module

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/python-scripts#2]
build and publish our python xena API, so that others and ourself can write python code connect to xenahub. 

start with https://github.com/jingchunzhu/cgDataNew/tree/master/xena
materials to include in the package or module:

xenaQuery.py
xenaAPI.py
dataset_obj/

name of module: xenaPython

**Comment by GiriB** [comment]
@jingchunzhu  @maryjgoldman I created a package `xenaPythonTest` on the [PyPi Test](https://testpypi.python.org/pypi). It can be installed as `pip install -i https://testpypi.python.org/pypitest xenaPythonTest `.

The code and usage instructions are [here](https://github.com/GiriB/xenaPythonTest).

`dataset_obj/` is not yet available since PyPi doesn't download any files other than `*.py` by default. However there [is a way to do it](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files).  

My next step would be to include `dataset_obj/` too.

@jingchunzhu  Could you try to use the `xenaPythonTest` package and let me know if everything works as expected. This is my first time publishing a package on PyPi 🤞.

**Comment by GiriB** [comment]
@jingchunzhu @maryjgoldman I have [made the changes](https://github.com/GiriB/xenaPythonTest) to the download `dataset_obj/` when the user does `pip install`. The `dataset_obj/` objects would be available under the `site_packages/` directory. 

After a review (and making sure everything works fine ), we can move the package from  [PyPi Test](https://testpypi.python.org/pypi) to [PyPi](https://pypi.python.org/pypi) .

**Comment by jingchunzhu** [comment]
@GiriB Thank you so much for your contribution! I learned from your code how to build a python module. It is now published on PyPi.

I committed the xenaPython repo https://github.com/ucscXena/xenaPython, where there is an acknowledgement section with reference to your github homepage.
